# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Clone repository
      #   uses: actions/checkout@v2
      # - name: Use Node.js 18.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 18.x
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run build
      - name: move to build
        run: cd ..
      - name: pwd
        run: pwd
      - name: delivery build to 
        run: scp -r -i "tpsecurity.pem" ./security-landing-page/build/*  ubuntu@ec2-13-213-60-120.ap-southeast-1.compute.amazonaws.com:/var/www/tpsecurity/html
